remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [OSINT Sage]
description: [Living Somewhere Between 1's And 0's]